line-length = 100
target-version = "py312"

[lint]
select = ["E", "F", "W", "I"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"

[lint.isort]
combine-as-imports = true
known-first-party = ["dev_environment"]

[lint.per-file-ignores]
"tests/*" = ["E501"]
